### ISSUE TITLE
Při výpočtu jednoho bodu není nutné udržovat pole vah, stačí dvě proměnné

### ISSUE THREAD

**Issue by xtompok** [nomaaad/Uvod-do-programovani-Java#13]

**Comment by nomaaad** [comment]
Mně se řešení s polem líbilo, bylo inspirované doc. Ježkem. 
Dej vědět, jestli je to nové (nezakomentované) řešení lepší.

**Comment by xtompok** [comment]
Je to lepší, ještě se dají ty 2 for cykly spojit do jednoho a bude to ideální. Vytvářet si pomocné pole stojí docela dost paměti a je to zbytečné. V MatLabu to je intuitivnější s poli, protože je program na výpočet s poli, ale v běžných jazycích bude řešení bez polí výrazně rychlejší, protože stejně pole po výpočtu bodu zahodíš, takže si ani nepomůžeš tím, že bys něco nemusel znovu počítat.
