### ISSUE TITLE
Iterativní výpočet v getGrid může mít aditivní chybu

### ISSUE THREAD

**Issue by xtompok** [nomaaad/Uvod-do-programovani-Java#15]
Pokud se cell nějakým způsobem zaokrouhlí, tak pokud bude síť velká, tak se tato chyba může významným způsobem nasčítat. Zkus si porovnat grid[res-1] s getMax(arr), o kolik se liší.
Lépe je počítat mezilehlé body pomocí poměru (počet buněk od minima)/(počet buněk celkem), pak se chyby nesčítají.

**Comment by nomaaad** [comment]
Opraveno na poměr. Rozdíl mezi grid[res-1] s getMax(arr) je velikost 1 buňky, což by mělo být správně.
